# Nombre de tu pipeline
name: Pipeline de Integración Continua

# Define cuándo se va a ejecutar (en cada push a la rama main)
on:
  push:
    branches: [ "main" ]

# Define los trabajos (jobs) que se van a realizar
jobs:
  build:
    # Usa una máquina virtual de Ubuntu para ejecutar los pasos
    runs-on: ubuntu-latest

    # Define la secuencia de pasos que se ejecutarán
    steps:
      # Paso 1: Descargar tu código
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      # Paso 2: Instalar Node.js
      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Paso 3: Instalar dependencias del Backend
      - name: Instalar dependencias del Backend
        run: |
          echo ">>> Iniciando instalación de dependencias del backend..."
          npm install --prefix ./backend

      # Paso 4: Instalar dependencias del Frontend
      - name: Instalar dependencias del Frontend
        run: |
          echo ">>> Iniciando instalación de dependencias del frontend..."
          npm install --prefix ./client/ccabello_cliente

      # Paso 5: Ejecutar pruebas
      - name: Ejecutar pruebas del Frontend
        run: |
          echo ">>> Ejecutando pruebas unitarias con Vitest..."
          npm test --prefix ./client/ccabello_cliente

      # Paso 6: Compilar la aplicación
      - name: Compilar Frontend para producción
        run: |
          echo ">>> Compilando la aplicación de React con Vite..."
          npm run build --prefix ./client/ccabello_cliente
          echo ">>> ¡Compilación finalizada con éxito!"