name: Pipeline de Integración Continua

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependencias del Backend
        run: npm install --prefix ./backend

      - name: Instalar dependencias del Frontend
        run: npm install --prefix ./client/ccabello_cliente

      - name: Ejecutar pruebas del Frontend
        run: npm test --prefix ./client/ccabello_cliente

      - name: Compilar Frontend para producción
        run: npm run build --prefix ./client/ccabello_cliente